export default {
walks:[{
  id:1,
  walk_name:"Abel Tasman Coast Track",
  description: "60 km one way / 3 - 5 days / Intermediate",
  full_walk: 1,
  pdf_url: "./public/pdfs/abel-tasman.pdf",
  lat:-40.909,
  lng:173.048},
  {
  id:2,
  walk_name:"Heaphy Track",
  description:"78.4 km one way / 4 - 6 days / Intermediate",full_walk:1,
  pdf_url:"./public/pdfs/heaphy.pdf",
  lat:-40.886,
  lng:172.303},
{
  id:3,
  walk_name:"Kepler Track",
  description:"60 km loop / 3 - 4 days / Intermediate",
  full_walk:1,
  pdf_url:"./public/pdfs/kepler.pdf",
  lat:-45.451,
  lng:167.575},
{
  id:4,
  walk_name:"Lake Waikaremoana",
  description:"46 km one way/ 3 - 4 days / Intermediate",
  full_walk:1,
  pdf_url:"./public/pdfs/waikaremoana.pdf",
  lat:-38.801,
  lng:177.115},
{
  id:5,
  walk_name:"Milford Track",
  description:"53.5 km one way / 4 days / Intermediate",
  full_walk:1,
  pdf_url:"./public/pdfs/milford.pdf",
  lat:-44.828,
  lng:167.793},
{
  id:6,
  walk_name:"Rakiura Track",
  description:"32 km loop / 3 days / Intermediate",
  full_walk:1,
  pdf_url:"./public/pdfs/rakiura.pdf",
  lat:-46.684,
  lng:167.868},
{
  id:7,
  walk_name:"Routeburn Track",
  description:"32 km one way / 2 - 4 days / Intermediate",
  full_walk:1,
  pdf_url:"./public/pdfs/routeburn.pdf",
  lat:-44.781,
  lng:168.163},
{
  id:8,
  walk_name:"Tongariro Northern Circuit",
  description:"43.1 km loop / 3-4 days / Intermediate",
  full_walk:1,
  pdf_url:"./public/pdfs/tongariro.pdf",
  lat:-39.209,
  lng:175.68},
{
  id:9,
  walk_name:"Whanganui Journey",
  description:"87 or 145 km one way / 3 or 5 days / Kayaking and canoeing",
  full_walk:1,
  pdf_url:"./public/pdfs/whanganui.pdf",
  lat:-39.209,
  lng:175.68}],

  activities:[{"id":1,"walk_id":4,"description":"Onepoto to Panekire Hut Lookout walk","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/east-coast/places/te-urewera/things-to-do/tracks/lake-waikaremoana-great-walk/"},{"id":2,"walk_id":4,"description":"Hinerau Walk","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/east-coast/places/te-urewera/things-to-do/tracks/lake-waikaremoana-great-walk/"},{"id":3,"walk_id":4,"description":"Aniwaniwa Falls Track","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/east-coast/places/te-urewera/things-to-do/tracks/lake-waikaremoana-great-walk/"},{"id":4,"walk_id":4,"description":"Papakorito Falls","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/east-coast/places/te-urewera/things-to-do/tracks/lake-waikaremoana-great-walk/"},{"id":5,"walk_id":1,"description":"Cascade Falls","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/nelson-tasman/places/abel-tasman-national-park/things-to-do/tracks/abel-tasman-coast-track/"},{"id":6,"walk_id":1,"description":"Awaroa Beach","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/nelson-tasman/places/abel-tasman-national-park/things-to-do/tracks/abel-tasman-coast-track/"},{"id":7,"walk_id":1,"description":"Cleopatras Pool","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/nelson-tasman/places/abel-tasman-national-park/things-to-do/tracks/abel-tasman-coast-track/"},{"id":8,"walk_id":1,"description":"Kayaking between the bays","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/nelson-tasman/places/abel-tasman-national-park/things-to-do/tracks/abel-tasman-coast-track/"},{"id":9,"walk_id":2,"description":"Mountain bike the track in the winter season","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/nelson-tasman/places/kahurangi-national-park/things-to-do/tracks/heaphy-track/"},{"id":10,"walk_id":2,"description":"Flanagans Corner","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/nelson-tasman/places/kahurangi-national-park/things-to-do/tracks/heaphy-track/"},{"id":11,"walk_id":2,"description":"The ‘enchanted forest’","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/nelson-tasman/places/kahurangi-national-park/things-to-do/tracks/heaphy-track/"},{"id":12,"walk_id":3,"description":"Iris Burn Waterfall","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/fiordland/places/fiordland-national-park/things-to-do/tracks/kepler-track/"},{"id":13,"walk_id":3,"description":"Luxmore Cave","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/fiordland/places/fiordland-national-park/things-to-do/tracks/kepler-track/"},{"id":14,"walk_id":5,"description":"Sutherland Falls","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/fiordland/places/fiordland-national-park/things-to-do/tracks/milford-track/"},{"id":15,"walk_id":5,"description":"Giants Gate Falls","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/fiordland/places/fiordland-national-park/things-to-do/tracks/milford-track/"},{"id":16,"walk_id":5,"description":"Andersons Cascade","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/fiordland/places/fiordland-national-park/things-to-do/tracks/milford-track/"},{"id":17,"walk_id":5,"description":"Pompolona ice field","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/fiordland/places/fiordland-national-park/things-to-do/tracks/milford-track/"},{"id":18,"walk_id":5,"description":"Emerald waters of the Clinton River","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/fiordland/places/fiordland-national-park/things-to-do/tracks/milford-track/"},{"id":19,"walk_id":6,"description":" Ulva Island/Te Wharawhara","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/southland/places/stewart-island-rakiura/rakiura-national-park/things-to-do/rakiura-track/"},{"id":20,"walk_id":6,"description":"Port William/Potirepo","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/southland/places/stewart-island-rakiura/rakiura-national-park/things-to-do/rakiura-track/"},{"id":21,"walk_id":6,"description":"Maori Beach","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/southland/places/stewart-island-rakiura/rakiura-national-park/things-to-do/rakiura-track/"},{"id":22,"walk_id":6,"description":"Paterson Inlet/Whaka a Te Wera","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/southland/places/stewart-island-rakiura/rakiura-national-park/things-to-do/rakiura-track/"},{"id":23,"walk_id":7,"description":"Bridal Veil Waterfall","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/fiordland/places/fiordland-national-park/things-to-do/tracks/routeburn-track/"},{"id":24,"walk_id":7,"description":"Humboldt Mountains","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/fiordland/places/fiordland-national-park/things-to-do/tracks/routeburn-track/"},{"id":25,"walk_id":7,"description":"Lake Mackenzie","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/fiordland/places/fiordland-national-park/things-to-do/tracks/routeburn-track/"},{"id":26,"walk_id":7,"description":"Darran Mountains","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/fiordland/places/fiordland-national-park/things-to-do/tracks/routeburn-track/"},{"id":27,"walk_id":8,"description":"Taranaki Falls","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/central-north-island/places/tongariro-national-park/things-to-do/tracks/tongariro-northern-circuit/"},{"id":28,"walk_id":8,"description":"Mt Tongariro Summit","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/central-north-island/places/tongariro-national-park/things-to-do/tracks/tongariro-northern-circuit/"},{"id":29,"walk_id":8,"description":"Tama Lakes","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/central-north-island/places/tongariro-national-park/things-to-do/tracks/tongariro-northern-circuit/"},{"id":30,"walk_id":8,"description":"Emerald Lakes","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/central-north-island/places/tongariro-national-park/things-to-do/tracks/tongariro-northern-circuit/"},{"id":31,"walk_id":8,"description":"Blue Lake","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/central-north-island/places/tongariro-national-park/things-to-do/tracks/tongariro-northern-circuit/"},{"id":32,"walk_id":9,"description":"Ohura River and Falls","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/manawatu-whanganui/places/whanganui-national-park/things-to-do/tracks/whanganui-journey/"},{"id":33,"walk_id":9,"description":"Tamatea’s Cave","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/manawatu-whanganui/places/whanganui-national-park/things-to-do/tracks/whanganui-journey/"},{"id":34,"walk_id":9,"description":"The Bridge to Nowhere","url":"http://www.doc.govt.nz/parks-and-recreation/places-to-go/manawatu-whanganui/places/whanganui-national-park/things-to-do/tracks/whanganui-journey/"}]
}
